# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/06/11 17:22:46 by lde-san-          #+#    #+#              #
#    Updated: 2025/06/11 17:22:51 by lde-san-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= echoer

MINT	= \033[38;2;55;250;133;48;2;0;0;0m
NEOR	= \033[3m\033[38;2;255;153;51m
B_WI    = \033[1;37m
RESET	= \033[0m
BABY	= \033[38;2;0;255;247m
BLACK	= \033[38;2;0;0;0m

FILES	= make_echoes_echosed.c
FILES	+= get_next_line_bonus_echosed.c
FILES	+= get_next_line_utils_bonus.c

INC	= get_next_line_bonus.h

%.c:
	@$(MAKE) build_make_echoes.c build_get_next_line_bonus.c build_get_next_line_utils_bonus.c
	@printf "$(BLACK)"
%.h:
	@$(MAKE) build_get_next_line_bonus.h
	@printf "$(BLACK)"

$(NAME): $(INC) $(FILES)
	@cc -g -O0 $(FILES) -o $(NAME)
	@printf "$(BLACK)"
	@$(MAKE) clean
	@$(MAKE) info

info:
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second   🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.  🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second.. 🦝"
	@sleep 0.2
	@clear
	@printf "$(MINT)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\t🦝Almost done! Hang tight for a second...🦝"
	@sleep 0.2
	@clear
	@printf "$(RESET)"
	@clear
	@printf "\n"
	@printf "$(MINT)\n\t\t🦝 Hi, Thank you for getting the Echoer! 🦝\n\n"
	@printf "$(NEOR)\tTo use it, simply execute it with the name of a file. When you\n\tdo, you'll  see  that your  terminal  will  show  its content\n\t formatted for you. Simply copy this text into your makefile\n\t  and you'll see that when running it you'll create a copy\n\t   of  it  just  by  executing  the  corresponding  rule\n\n"
	@printf "$(B_WI)for more info, run$(BABY) 'make build_make_echoes.c' $(B_WI)and explore the file it creates\n$(BLACK)"

all: $(NAME)

clean:
	@rm -rf $(FILES) $(INC)
	
fclean: clean
	@rm -rf $(NAME)
	
re: fclean all

.PHONY: all clean fclean re info build_get_next_line_bonus.h build_get_next_line_utils_bonus.c build_get_next_line_bonus.c build_make_echoes.c


build_get_next_line_utils_bonus.c:
	@printf "$(NEOR) Building get_next_line_utils_bonus.c... $(RESET)"
	@printf "$(MINT)🦝\n\n"
	@> get_next_line_utils_bonus.c
	printf '/* ************************************************************************** */\n'>> get_next_line_utils_bonus.c
	printf '/*                                                                            */\n'>> get_next_line_utils_bonus.c
	printf '/*                                                        :::      ::::::::   */\n'>> get_next_line_utils_bonus.c
	printf '/*   get_next_line_utils_bonus.c                        :+:      :+:    :+:   */\n'>> get_next_line_utils_bonus.c
	printf '/*                                                    +:+ +:+         +:+     */\n'>> get_next_line_utils_bonus.c
	printf '/*   By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+        */\n'>> get_next_line_utils_bonus.c
	printf '/*                                                +#+#+#+#+#+   +#+           */\n'>> get_next_line_utils_bonus.c
	printf '/*   Created: 2025/05/28 22:38:33 by lde-san-          #+#    #+#             */\n'>> get_next_line_utils_bonus.c
	printf '/*   Updated: 2025/06/03 12:25:07 by lde-san-         ###   ########.fr       */\n'>> get_next_line_utils_bonus.c
	printf '/*                                                                            */\n'>> get_next_line_utils_bonus.c
	printf '/* ************************************************************************** */\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '#include "get_next_line_bonus.h"\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf 't_lst	*racc_lstnew(char c)\n'>> get_next_line_utils_bonus.c
	@printf '{\n'>> get_next_line_utils_bonus.c
	@printf '	t_lst	*result;\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '	result = malloc(sizeof (t_lst));\n'>> get_next_line_utils_bonus.c
	@printf '	if (!result)\n'>> get_next_line_utils_bonus.c
	@printf '		return (NULL);\n'>> get_next_line_utils_bonus.c
	@printf '	result -> letter = c;\n'>> get_next_line_utils_bonus.c
	@printf '	result -> next = NULL;\n'>> get_next_line_utils_bonus.c
	@printf '	result -> tail = NULL;\n'>> get_next_line_utils_bonus.c
	@printf '	return (result);\n'>> get_next_line_utils_bonus.c
	@printf '}\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf 'size_t	racc_linesize(t_lst *lst)\n'>> get_next_line_utils_bonus.c
	@printf '{\n'>> get_next_line_utils_bonus.c
	@printf '	size_t	count;\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '	count = 0;\n'>> get_next_line_utils_bonus.c
	@printf '	while (lst)\n'>> get_next_line_utils_bonus.c
	@printf '	{\n'>> get_next_line_utils_bonus.c
	@printf '		count++;\n'>> get_next_line_utils_bonus.c
	@printf '		if (lst -> letter == '\'''\\\\'n'\'')\n'>> get_next_line_utils_bonus.c
	@printf '			break ;\n'>> get_next_line_utils_bonus.c
	@printf '		lst = lst -> next;\n'>> get_next_line_utils_bonus.c
	@printf '	}\n'>> get_next_line_utils_bonus.c
	@printf '	return (count);\n'>> get_next_line_utils_bonus.c
	@printf '}\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf 'int	racc_findend(t_lst **lst)\n'>> get_next_line_utils_bonus.c
	@printf '{\n'>> get_next_line_utils_bonus.c
	@printf '	t_lst	*traveler;\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '	if (!*lst)\n'>> get_next_line_utils_bonus.c
	@printf '		return (-1);\n'>> get_next_line_utils_bonus.c
	@printf '	traveler = *lst;\n'>> get_next_line_utils_bonus.c
	@printf '	while (traveler)\n'>> get_next_line_utils_bonus.c
	@printf '	{\n'>> get_next_line_utils_bonus.c
	@printf '		if (traveler -> letter == '\'''\\\\'n'\'')\n'>> get_next_line_utils_bonus.c
	@printf '			return (0);\n'>> get_next_line_utils_bonus.c
	@printf '		traveler = traveler -> next;\n'>> get_next_line_utils_bonus.c
	@printf '	}\n'>> get_next_line_utils_bonus.c
	@printf '	return (-1);\n'>> get_next_line_utils_bonus.c
	@printf '}\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf 'void	racc_delnode(t_lst **lst, int clear_all)\n'>> get_next_line_utils_bonus.c
	@printf '{\n'>> get_next_line_utils_bonus.c
	@printf '	t_lst	*temp;\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '	temp = NULL;\n'>> get_next_line_utils_bonus.c
	@printf '	while (*lst)\n'>> get_next_line_utils_bonus.c
	@printf '	{\n'>> get_next_line_utils_bonus.c
	@printf '		temp = (*lst)-> next;\n'>> get_next_line_utils_bonus.c
	@printf '		free(*lst);\n'>> get_next_line_utils_bonus.c
	@printf '		*lst = temp;\n'>> get_next_line_utils_bonus.c
	@printf '		if (clear_all == 0)\n'>> get_next_line_utils_bonus.c
	@printf '			return ;\n'>> get_next_line_utils_bonus.c
	@printf '	}\n'>> get_next_line_utils_bonus.c
	@printf '	*lst = NULL;\n'>> get_next_line_utils_bonus.c
	@printf '	return ;\n'>> get_next_line_utils_bonus.c
	@printf '}\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf 'int	racc_lstadd(t_lst **lst, t_lst *new)\n'>> get_next_line_utils_bonus.c
	@printf '{\n'>> get_next_line_utils_bonus.c
	@printf '	t_lst	*last;\n'>> get_next_line_utils_bonus.c
	@printf '\n'>> get_next_line_utils_bonus.c
	@printf '	if (!lst || !new)\n'>> get_next_line_utils_bonus.c
	@printf '		return (-1);\n'>> get_next_line_utils_bonus.c
	@printf '	if (!*lst)\n'>> get_next_line_utils_bonus.c
	@printf '	{\n'>> get_next_line_utils_bonus.c
	@printf '		*lst = new;\n'>> get_next_line_utils_bonus.c
	@printf '		(*lst)-> tail = new;\n'>> get_next_line_utils_bonus.c
	@printf '		return (0);\n'>> get_next_line_utils_bonus.c
	@printf '	}\n'>> get_next_line_utils_bonus.c
	@printf '	if (!(*lst)->tail)\n'>> get_next_line_utils_bonus.c
	@printf '	{\n'>> get_next_line_utils_bonus.c
	@printf '		last = *lst;\n'>> get_next_line_utils_bonus.c
	@printf '		while (last)\n'>> get_next_line_utils_bonus.c
	@printf '		{\n'>> get_next_line_utils_bonus.c
	@printf '			if (!(last -> next))\n'>> get_next_line_utils_bonus.c
	@printf '				break ;\n'>> get_next_line_utils_bonus.c
	@printf '			last = last -> next;\n'>> get_next_line_utils_bonus.c
	@printf '		}\n'>> get_next_line_utils_bonus.c
	@printf '		(*lst)-> tail = last;\n'>> get_next_line_utils_bonus.c
	@printf '	}\n'>> get_next_line_utils_bonus.c
	@printf '	(*lst)-> tail -> next = new;\n'>> get_next_line_utils_bonus.c
	@printf '	(*lst)-> tail = new;\n'>> get_next_line_utils_bonus.c
	@printf '	return (0);\n'>> get_next_line_utils_bonus.c
	@printf '}\n'>> get_next_line_utils_bonus.c
	@sleep 0.5
	@printf "$(RESET)🦝"

build_get_next_line_bonus.c:
	@printf "🦝 \001\033[3m\033[38;2;255;153;51m\002Building get_next_line_bonus_echosed.c... 🦝\\n"
	@> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                        :::      ::::::::   */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                        :::      ::::::::   */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'get_next_line_bonus.c                         ' '\001\033[1;38;2;0;255;247m\002' '     :+:      :+:    :+:   */' '\001\033[0m\002'
	@printf "%s\n" '/*   get_next_line_bonus.c                              :+:      :+:    :+:   */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                    +:+ +:+         +:+     */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                    +:+ +:+         +:+     */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'By: lde-san- <lde-san-@student.42porto.co     ' '\001\033[1;38;2;0;255;247m\002' ' +#+  +:+       +#+        */' '\001\033[0m\002'
	@printf "%s\n" '/*   By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+        */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                +#+#+#+#+#+   +#+           */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                +#+#+#+#+#+   +#+           */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Created: 2025/05/28 22:38:01 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '    #+#    #+#             */' '\001\033[0m\002'
	@printf "%s\n" '/*   Created: 2025/05/28 22:38:01 by lde-san-          #+#    #+#             */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Updated: 2025/06/03 12:24:51 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '   ###   ########.fr       */' '\001\033[0m\002'
	@printf "%s\n" '/*   Updated: 2025/06/03 12:24:51 by lde-san-         ###   ########.fr       */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> get_next_line_bonus_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '#include "get_next_line_bonus.h"' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" 'char	*get_lines(t_lst **head)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	t_lst	*traveler;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	size_t	guide;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	char	*line;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	size_t	line_len;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	line_len = racc_linesize(*head);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	line = malloc((line_len + 1) * sizeof (char));' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (!line)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (racc_delnode(head, 1), NULL);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	traveler = *head;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	guide = 0;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	while (guide < line_len)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		line[guide] = traveler -> letter;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		traveler = traveler -> next;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		racc_delnode(head, 0);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		guide++;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	}' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	line[guide] = '\''\0'\'';' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	return (line);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '}' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" 'int	extract_buffer(t_lst **head, int fd)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	ssize_t	read_out;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	ssize_t	guide;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	char	*buffer;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	buffer = malloc(BUFFER_SIZE * sizeof(char));' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (!buffer)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (-1);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	read_out = read(fd, buffer, BUFFER_SIZE);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (read_out < 0)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (free(buffer), -1);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (read_out == 0)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (free(buffer), 0);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	guide = 0;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	while (guide < read_out)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		if (racc_lstadd(head, racc_lstnew(buffer[guide])) == -1)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '			return (free(buffer), -1);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		guide++;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	}' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	free(buffer);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	return (1);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '}' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" 'char	*get_next_line(int fd)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	static t_lst	*head_hub[MAX_FD];' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	int				read_out;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (fd < 0 || BUFFER_SIZE <= 0 || fd >= MAX_FD)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (NULL);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	while (racc_findend(&head_hub[fd]) == -1)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	{' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		read_out = extract_buffer(&head_hub[fd], fd);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		if (read_out == 0)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '			break ;' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		if (read_out < 0)' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '			return (racc_delnode(&head_hub[fd], 1), NULL);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	}' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	if (!head_hub[fd])' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '		return (NULL);' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '	return (get_lines(&head_hub[fd]));' >> get_next_line_bonus_echosed.c
	@printf "%s\n" '}' >> get_next_line_bonus_echosed.c
	@printf "\033[0m\t🦝\n"

build_get_next_line_bonus.h:
	@printf "🦝 \001\033[3m\033[38;2;255;153;51m\002Building get_next_line_bonus.h... 🦝\\n"
	@> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                        :::      ::::::::   */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                        :::      ::::::::   */' >> get_next_line_bonus.h
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'get_next_line_bonus.h                         ' '\001\033[1;38;2;0;255;247m\002' '     :+:      :+:    :+:   */' '\001\033[0m\002'
	@printf "%s\n" '/*   get_next_line_bonus.h                              :+:      :+:    :+:   */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                    +:+ +:+         +:+     */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                    +:+ +:+         +:+     */' >> get_next_line_bonus.h
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'By: lde-san- <lde-san-@student.42porto.co     ' '\001\033[1;38;2;0;255;247m\002' ' +#+  +:+       +#+        */' '\001\033[0m\002'
	@printf "%s\n" '/*   By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+        */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                +#+#+#+#+#+   +#+           */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                +#+#+#+#+#+   +#+           */' >> get_next_line_bonus.h
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Created: 2025/05/28 22:39:01 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '    #+#    #+#             */' '\001\033[0m\002'
	@printf "%s\n" '/*   Created: 2025/05/28 22:39:01 by lde-san-          #+#    #+#             */' >> get_next_line_bonus.h
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Updated: 2025/10/09 10:01:23 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '   ###   ########.fr       */' '\001\033[0m\002'
	@printf "%s\n" '/*   Updated: 2025/10/09 10:01:23 by lde-san-         ###   ########.fr       */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> get_next_line_bonus.h
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" '#ifndef GET_NEXT_LINE_BONUS_H' >> get_next_line_bonus.h
	@printf "%s\n" '# define GET_NEXT_LINE_BONUS_H' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" '# ifndef BUFFER_SIZE' >> get_next_line_bonus.h
	@printf "%s\n" '#  define BUFFER_SIZE 42' >> get_next_line_bonus.h
	@printf "%s\n" '# endif' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" '# ifndef MAX_FD' >> get_next_line_bonus.h
	@printf "%s\n" '#  define MAX_FD 1024' >> get_next_line_bonus.h
	@printf "%s\n" '# endif' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" '# include <stdlib.h>' >> get_next_line_bonus.h
	@printf "%s\n" '# include <stdio.h>' >> get_next_line_bonus.h
	@printf "%s\n" '# include <fcntl.h>' >> get_next_line_bonus.h
	@printf "%s\n" '# include <unistd.h>' >> get_next_line_bonus.h
	@printf "%s\n" '# include <stddef.h>' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" 'typedef struct s_lst' >> get_next_line_bonus.h
	@printf "%s\n" '{' >> get_next_line_bonus.h
	@printf "%s\n" '	char			letter;' >> get_next_line_bonus.h
	@printf "%s\n" '	struct s_lst	*tail;' >> get_next_line_bonus.h
	@printf "%s\n" '	struct s_lst	*next;' >> get_next_line_bonus.h
	@printf "%s\n" '}	t_lst;' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" 'char	*get_next_line(int fd);' >> get_next_line_bonus.h
	@printf "%s\n" 'int		extract_buffer(t_lst **head, int fd);' >> get_next_line_bonus.h
	@printf "%s\n" 'char	*get_lines(t_lst **head);' >> get_next_line_bonus.h
	@printf "%s\n" 't_lst	*racc_lstnew(char c);' >> get_next_line_bonus.h
	@printf "%s\n" 'size_t	racc_linesize(t_lst *lst);' >> get_next_line_bonus.h
	@printf "%s\n" 'int		racc_findend(t_lst **lst);' >> get_next_line_bonus.h
	@printf "%s\n" 'void	racc_delnode(t_lst **lst, int clear_all);' >> get_next_line_bonus.h
	@printf "%s\n" 'int		racc_lstadd(t_lst **lst, t_lst *new);' >> get_next_line_bonus.h
	@printf "%s\n" '' >> get_next_line_bonus.h
	@printf "%s\n" '#endif' >> get_next_line_bonus.h
	@printf "\033[0m\t🦝\n"

build_make_echoes.c:
	@printf "🦝 \001\033[3m\033[38;2;255;153;51m\002Building make_echoes_echosed.c... 🦝\\n"
	@> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                        :::      ::::::::   */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                        :::      ::::::::   */' >> make_echoes_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'make_echoes_echosed.c                         ' '\001\033[1;38;2;0;255;247m\002' '     :+:      :+:    :+:   */' '\001\033[0m\002'
	@printf "%s\n" '/*   make_echoes_echosed.c                              :+:      :+:    :+:   */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                    +:+ +:+         +:+     */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                    +:+ +:+         +:+     */' >> make_echoes_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;55;250;133m\002' 'By: lde-san- <lde-san-@student.42porto.co     ' '\001\033[1;38;2;0;255;247m\002' ' +#+  +:+       +#+        */' '\001\033[0m\002'
	@printf "%s\n" '/*   By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+        */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                +#+#+#+#+#+   +#+           */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                +#+#+#+#+#+   +#+           */' >> make_echoes_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Created: 2025/06/08 15:18:45 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '    #+#    #+#             */' '\001\033[0m\002'
	@printf "%s\n" '/*   Created: 2025/06/08 15:18:45 by lde-san-          #+#    #+#             */' >> make_echoes_echosed.c
	@printf "%b%s%b%s%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*   ' '\001\033[1;38;2;0;255;0m\002' 'Updated: 2025/10/09 10:51:54 by lde-san-      ' '\001\033[1;38;2;0;255;247m\002' '   ###   ########.fr       */' '\001\033[0m\002'
	@printf "%s\n" '/*   Updated: 2025/10/09 10:51:54 by lde-san-         ###   ########.fr       */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/*                                                                            */' '\001\033[0m\002'
	@printf "%s\n" '/*                                                                            */' >> make_echoes_echosed.c
	@printf "%b%s%b\n" '\001\033[1;38;2;0;255;247m\002' '/* ************************************************************************** */' '\001\033[0m\002'
	@printf "%s\n" '/* ************************************************************************** */' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" '#include "get_next_line_bonus.h"' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" '#define RSET	"\033[0m"' >> make_echoes_echosed.c
	@printf "%s\n" '#define B_WI    "\033[1;37m"' >> make_echoes_echosed.c
	@printf "%s\n" '#define BABY	"\033[38;2;0;255;247m"' >> make_echoes_echosed.c
	@printf "%s\n" '#define MINT	"\033[38;2;55;250;133m"' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" '/*TLDR; This program requires the get_next_line_bonus function. It uses it to read' >> make_echoes_echosed.c
	@printf "%s\n" 'each line from the selected file so it can be printed while simultaneously formated' >> make_echoes_echosed.c
	@printf "%s\n" 'in a way that the file can be converted into a makefile rule. The result of running' >> make_echoes_echosed.c
	@printf "%s\n" 'this program with the name of a file present in the directory, should be an output ' >> make_echoes_echosed.c
	@printf "%s\n" 'on the terminal that can be copy and pasted into the desired makefile. Enjoy <3*/' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" 'size_t str_len(char *str)' >> make_echoes_echosed.c
	@printf "%s\n" '{' >> make_echoes_echosed.c
	@printf "%s\n" '	size_t guide;' >> make_echoes_echosed.c
	@printf "%s\n" '	' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	' >> make_echoes_echosed.c
	@printf "%s\n" '	if (!str)' >> make_echoes_echosed.c
	@printf "%s\n" '		return (0);' >> make_echoes_echosed.c
	@printf "%s\n" '	while(str[guide])' >> make_echoes_echosed.c
	@printf "%s\n" '	{' >> make_echoes_echosed.c
	@printf "%s\n" '		guide++;' >> make_echoes_echosed.c
	@printf "%s\n" '	}' >> make_echoes_echosed.c
	@printf "%s\n" '	return(guide);' >> make_echoes_echosed.c
	@printf "%s\n" '}' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" 'char    *rputnum(long n)' >> make_echoes_echosed.c
	@printf "%s\n" '{' >> make_echoes_echosed.c
	@printf "%s\n" '    static char buf[32];' >> make_echoes_echosed.c
	@printf "%s\n" '    char        *p = buf + 31;' >> make_echoes_echosed.c
	@printf "%s\n" '    int         neg = (n < 0);' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" '    *p = '\''\0'\'';' >> make_echoes_echosed.c
	@printf "%s\n" '    if (neg)' >> make_echoes_echosed.c
	@printf "%s\n" '        n = -n;' >> make_echoes_echosed.c
	@printf "%s\n" '    do {' >> make_echoes_echosed.c
	@printf "%s\n" '        *--p = '\''0'\'' + (n % 10);' >> make_echoes_echosed.c
	@printf "%s\n" '        n /= 10;' >> make_echoes_echosed.c
	@printf "%s\n" '    } while (n > 0);' >> make_echoes_echosed.c
	@printf "%s\n" '    if (neg)' >> make_echoes_echosed.c
	@printf "%s\n" '        *--p = '\''-'\'';' >> make_echoes_echosed.c
	@printf "%s\n" '    return (p);' >> make_echoes_echosed.c
	@printf "%s\n" '}' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" 'int compare(char *s1, char *s2)' >> make_echoes_echosed.c
	@printf "%s\n" '{' >> make_echoes_echosed.c
	@printf "%s\n" '	size_t guide;' >> make_echoes_echosed.c
	@printf "%s\n" '	' >> make_echoes_echosed.c
	@printf "%s\n" '	if (!s1 || !s2)' >> make_echoes_echosed.c
	@printf "%s\n" '		return(0);' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	if (str_len(s1) == str_len(s2))' >> make_echoes_echosed.c
	@printf "%s\n" '	{' >> make_echoes_echosed.c
	@printf "%s\n" '		while ((s1[guide] == s2[guide]) && (s1[guide] && s2[guide]))' >> make_echoes_echosed.c
	@printf "%s\n" '			guide++;' >> make_echoes_echosed.c
	@printf "%s\n" '	}' >> make_echoes_echosed.c
	@printf "%s\n" '	if (!(s1[guide]) && !(s2[guide]))' >> make_echoes_echosed.c
	@printf "%s\n" '		return (1);' >> make_echoes_echosed.c
	@printf "%s\n" '	return (0);' >> make_echoes_echosed.c
	@printf "%s\n" '}' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" 'int main( int arc, char **wordy)' >> make_echoes_echosed.c
	@printf "%s\n" '{' >> make_echoes_echosed.c
	@printf "%s\n" '	long line_num;' >> make_echoes_echosed.c
	@printf "%s\n" '	int fd;' >> make_echoes_echosed.c
	@printf "%s\n" '	char *line;' >> make_echoes_echosed.c
	@printf "%s\n" '	int guide;' >> make_echoes_echosed.c
	@printf "%s\n" '	char *head_check = "/* ************************************************************************** */\n";' >> make_echoes_echosed.c
	@printf "%s\n" '	int hat_shoe;' >> make_echoes_echosed.c
	@printf "%s\n" '	' >> make_echoes_echosed.c
	@printf "%s\n" '	if (arc != 2)' >> make_echoes_echosed.c
	@printf "%s\n" '		return (write(1, "No la das mrk: Incorrect argument count", 39), 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	' >> make_echoes_echosed.c
	@printf "%s\n" '	fd = open(wordy[1], O_RDONLY);' >> make_echoes_echosed.c
	@printf "%s\n" '	if (fd < 0)' >> make_echoes_echosed.c
	@printf "%s\n" '		return (1);' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, B_WI, str_len(B_WI));' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "build_", 7);' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, ":\n", 2);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "\t@printf \"$$(NEOR) Building ", 27);' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "... $$(RESET)\"\n\t@printf \"$$(MINT)🦝\\n\\n\"\n\t@> ", 45);' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "\n", 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	hat_shoe = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	line_num = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	while((line = get_next_line(fd)) != NULL)' >> make_echoes_echosed.c
	@printf "%s\n" '	{	' >> make_echoes_echosed.c
	@printf "%s\n" '		if (compare(head_check, line) == 1)' >> make_echoes_echosed.c
	@printf "%s\n" '				hat_shoe++;' >> make_echoes_echosed.c
	@printf "%s\n" '		if (hat_shoe == 1)' >> make_echoes_echosed.c
	@printf "%s\n" '		{' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, BABY, str_len(BABY));' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, "\tprintf \"%s\\n\" \'\''", 16);' >> make_echoes_echosed.c
	@printf "%s\n" '		}' >> make_echoes_echosed.c
	@printf "%s\n" '		else if (hat_shoe > 1 || hat_shoe == 0)' >> make_echoes_echosed.c
	@printf "%s\n" '		{' >> make_echoes_echosed.c
	@printf "%s\n" '			if (hat_shoe == 2)' >> make_echoes_echosed.c
	@printf "%s\n" '			{' >> make_echoes_echosed.c
	@printf "%s\n" '				hat_shoe++;' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\tprintf \"%s\\n\" \'\''", 16);' >> make_echoes_echosed.c
	@printf "%s\n" '			}' >> make_echoes_echosed.c
	@printf "%s\n" '			else' >> make_echoes_echosed.c
	@printf "%s\n" '			{' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, MINT, str_len(MINT));' >> make_echoes_echosed.c
	@printf "%s\n" '				line_num++;' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\t@sed -i \'\''", str_len("\t@sed -i \'\''"));' >> make_echoes_echosed.c
	@printf "%s\n" '				if (line_num >= 1 && line_num < 10)' >> make_echoes_echosed.c
	@printf "%s\n" '					write(1,rputnum(line_num), 1);' >> make_echoes_echosed.c
	@printf "%s\n" '				else if (line_num >= 10 && line_num < 100)' >> make_echoes_echosed.c
	@printf "%s\n" '					write(1,rputnum(line_num), 2);' >> make_echoes_echosed.c
	@printf "%s\n" '				else if(line_num >= 100 && line_num < 1000)' >> make_echoes_echosed.c
	@printf "%s\n" '					write(1,rputnum(line_num), 3);' >> make_echoes_echosed.c
	@printf "%s\n" '				else if (line_num >= 1000 && line_num < 10000)' >> make_echoes_echosed.c
	@printf "%s\n" '					write(1,rputnum(line_num), 4);' >> make_echoes_echosed.c
	@printf "%s\n" '				else if (line_num >= 10000 && line_num < 100000)' >> make_echoes_echosed.c
	@printf "%s\n" '					write(1,rputnum(line_num), 5);' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "s/.*/", str_len("s/.*/"));' >> make_echoes_echosed.c
	@printf "%s\n" '			}' >> make_echoes_echosed.c
	@printf "%s\n" '		}' >> make_echoes_echosed.c
	@printf "%s\n" '		guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '		while(line[guide])' >> make_echoes_echosed.c
	@printf "%s\n" '		{' >> make_echoes_echosed.c
	@printf "%s\n" '		        if (line[guide] == '\''\n'\'')' >> make_echoes_echosed.c
	@printf "%s\n" '		                break ;' >> make_echoes_echosed.c
	@printf "%s\n" '			else if (line[guide] == 39)' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\'\''\\\'\''\'\''", 4);' >> make_echoes_echosed.c
	@printf "%s\n" '			else if (line[guide] == 37)' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\'\''\\%\'\''", 4);' >> make_echoes_echosed.c
	@printf "%s\n" '			else if (line[guide] == 34)' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\'\''\\\"\'\''", 4);' >> make_echoes_echosed.c
	@printf "%s\n" '			else if (line[guide] == 36)' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "$$$$", 2);' >> make_echoes_echosed.c
	@printf "%s\n" '			else if (line[guide] == 92)' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, "\'\''\\\\\'\''", 4);' >> make_echoes_echosed.c
	@printf "%s\n" '			else' >> make_echoes_echosed.c
	@printf "%s\n" '				write(1, &line[guide], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '			guide++;' >> make_echoes_echosed.c
	@printf "%s\n" '		}' >> make_echoes_echosed.c
	@printf "%s\n" '		free(line);' >> make_echoes_echosed.c
	@printf "%s\n" '		guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '		write(1, "/\'\'' ", 3);' >> make_echoes_echosed.c
	@printf "%s\n" '		while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	        write(1, "\n", 1);		' >> make_echoes_echosed.c
	@printf "%s\n" '	}' >> make_echoes_echosed.c
	@printf "%s\n" '	if(!(((wordy[1][str_len(wordy[1]) - 1] == '\''c'\'') || (wordy[1][str_len(wordy[1]) - 1] == '\''h'\'')) && (wordy[1][str_len(wordy[1]) - 2] == '\''.'\'')))' >> make_echoes_echosed.c
	@printf "%s\n" '	{' >> make_echoes_echosed.c
	@printf "%s\n" '		write(1, "\t@chmod 777 ", 12);' >> make_echoes_echosed.c
	@printf "%s\n" '		guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '		while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '		write(1, "\n", 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	}' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "\t@open ", 7);' >> make_echoes_echosed.c
	@printf "%s\n" '	guide = 0;' >> make_echoes_echosed.c
	@printf "%s\n" '	while (wordy[1][guide])' >> make_echoes_echosed.c
	@printf "%s\n" '			write(1, &wordy[1][guide++], 1);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, "\n", 1);' >> make_echoes_echosed.c
	@printf "%s\n" '		write(1, "\t@printf \"$$(RESET)🦝\"\n", 24);' >> make_echoes_echosed.c
	@printf "%s\n" '	write(1, RSET, str_len(RSET));' >> make_echoes_echosed.c
	@printf "%s\n" '	close(fd);' >> make_echoes_echosed.c
	@printf "%s\n" '	return(0);' >> make_echoes_echosed.c
	@printf "%s\n" '}' >> make_echoes_echosed.c
	@printf "%s\n" '' >> make_echoes_echosed.c
	@printf "\033[0m\t🦝\n"

