#!/bin/bash
# save_profile_snapshot.sh
# This script generates an executable that recreates your current GNOME Terminal profile.

# Get current profile UUID
CURRENT_UUID=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
if [ -z "$CURRENT_UUID" ]; then
    echo "🦝 Could not detect current profile UUID. 🦝"
    exit 1
fi

# Ask for a name for the snapshot file and the profile
read -rp "🦝 Enter a name for this snapshot file (Ex:, my_snapshot.sh): " SNAPSHOT_FILE
if [ -z "$SNAPSHOT_FILE" ]; then
    echo "🦝 Snapshot file name cannot be empty.🦝"
    exit 1
fi

read -rp "🦝 Name your profile: " PROFILE_NAME
if [ -z "$PROFILE_NAME" ]; then
    echo "🦝 Profile name cannot be empty. 🦝"
    exit 1
fi

# Ensure the snapshot file ends with .sh
[[ $SNAPSHOT_FILE != *.sh ]] && SNAPSHOT_FILE="${SNAPSHOT_FILE}.sh"

# Collect keys and values from the current profile
BASE_KEY="/org/gnome/terminal/legacy/profiles:/:$CURRENT_UUID/"
KEYS=$(gsettings list-keys org.gnome.Terminal.Legacy.Profile:"$BASE_KEY")

# Start generating the snapshot script
cat <<EOF > "$SNAPSHOT_FILE"
#!/bin/bash
# Generated by save_profile_snapshot.sh
# This script recreates the GNOME Terminal profile '$PROFILE_NAME'

NEW_UUID=\$(uuidgen)

# Add the new profile UUID to the list
CURRENT_LIST=\$(gsettings get org.gnome.Terminal.ProfilesList list)
CURRENT_LIST=\$(echo "\$CURRENT_LIST" | tr -d "[] ,")
NEW_LIST="\$CURRENT_LIST, '\$NEW_UUID'"
gsettings set org.gnome.Terminal.ProfilesList list "[\$NEW_LIST]"

# Set profile name
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:\$NEW_UUID/ visible-name "$PROFILE_NAME"

EOF

# Append all key-value pairs from the original profile
for key in $KEYS; do
    value=$(gsettings get org.gnome.Terminal.Legacy.Profile:"$BASE_KEY" "$key")
    # Escape single quotes inside the value
    value=${value//\'/\'\\\'\'}
    echo "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:\$NEW_UUID/ $key '$value'" >> "$SNAPSHOT_FILE"
done

# Make the generated script executable
chmod +x "$SNAPSHOT_FILE"
echo "🦝 Snapshot script '$SNAPSHOT_FILE' created! Run it to recreate profile '$PROFILE_NAME'. 🦝"

