#!/bin/bash
# Generated by save_profile_snapshot.sh
# This script recreates the GNOME Terminal profile 'racc_home'

NEW_UUID=$(uuidgen)

# Add the new profile UUID to the list
CURRENT_LIST=$(gsettings get org.gnome.Terminal.ProfilesList list)
CURRENT_LIST=$(echo "$CURRENT_LIST" | tr -d "[] ,")
NEW_LIST="$CURRENT_LIST, '$NEW_UUID'"
gsettings set org.gnome.Terminal.ProfilesList list "[$NEW_LIST]"

# Set profile name
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ visible-name "racc_home"

gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ audible-bell 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ background-color ''\''rgb(0,0,0)'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ background-transparency-percent '3'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ backspace-binding ''\''ascii-delete'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ bold-color ''\''#000000'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ bold-color-same-as-fg 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ bold-is-bright 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cell-height-scale '1.0'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cell-width-scale '1.0'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cjk-utf8-ambiguous-width ''\''narrow'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cursor-background-color ''\''#000000'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cursor-blink-mode ''\''system'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cursor-colors-set 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cursor-foreground-color ''\''#ffffff'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ cursor-shape ''\''block'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ custom-command ''\'''\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ default-size-columns '80'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ default-size-rows '24'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ delete-binding ''\''delete-sequence'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ enable-bidi 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ enable-shaping 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ enable-sixel 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ encoding ''\''UTF-8'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ exit-action ''\''close'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ font ''\''Monospace 12'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ foreground-color ''\''rgb(255,255,255)'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ highlight-background-color ''\''#000000'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ highlight-colors-set 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ highlight-foreground-color ''\''#ffffff'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ login-shell 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ palette '['\''rgb(23,20,33)'\'', '\''rgb(255,129,0)'\'', '\''rgb(38,162,105)'\'', '\''rgb(162,115,76)'\'', '\''rgb(30,255,205)'\'', '\''rgb(163,71,186)'\'', '\''rgb(0,255,250)'\'', '\''rgb(208,207,204)'\'', '\''rgb(94,92,100)'\'', '\''rgb(246,97,81)'\'', '\''rgb(51,218,122)'\'', '\''rgb(233,173,12)'\'', '\''rgb(42,123,222)'\'', '\''rgb(192,97,203)'\'', '\''rgb(51,199,222)'\'', '\''rgb(255,255,255)'\'']'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ preserve-working-directory ''\''safe'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ rewrap-on-resize 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scroll-on-insert 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scroll-on-keystroke 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scroll-on-output 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scrollback-lines '10000'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scrollback-unlimited 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ scrollbar-policy ''\''always'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ text-blink-mode ''\''always'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ use-custom-command 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ use-system-font 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ use-theme-colors 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ use-theme-transparency 'false'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ use-transparent-background 'true'
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ visible-name ''\''Unnamed'\'''
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$NEW_UUID/ word-char-exceptions '@ms nothing'
