# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/07 20:34:51 by lde-san-          #+#    #+#              #
#    Updated: 2025/04/07 20:44:30 by lde-san-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FILE = ft_display_file.c

COMPILE = cc -Wall -Werror -Wextra


all: $(NAME)

$(NAME): 
	$(COMPILE) $(FILE) -o $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
